// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    semesters,
    subjects,
    campuses,
    rooms,
    classSessions,
    sessionInstances,
    evaluations,
    userSettings,
  ];
  late final Shape0 semesters = Shape0(
      source: i0.VersionedTable(
        entityName: 'semesters',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 subjects = Shape1(
      source: i0.VersionedTable(
        entityName: 'subjects',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_5,
          _column_1,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 campuses = Shape2(
      source: i0.VersionedTable(
        entityName: 'campuses',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 rooms = Shape3(
      source: i0.VersionedTable(
        entityName: 'rooms',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 classSessions = Shape4(
      source: i0.VersionedTable(
        entityName: 'class_sessions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_22,
          _column_23,
          _column_24,
          _column_25,
          _column_26,
          _column_27,
          _column_28,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 sessionInstances = Shape5(
      source: i0.VersionedTable(
        entityName: 'session_instances',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(session_id, fecha)',
        ],
        columns: [
          _column_0,
          _column_29,
          _column_30,
          _column_31,
          _column_32,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 evaluations = Shape6(
      source: i0.VersionedTable(
        entityName: 'evaluations',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_22,
          _column_1,
          _column_33,
          _column_34,
          _column_35,
          _column_36,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 userSettings = Shape7(
      source: i0.VersionedTable(
        entityName: 'user_settings',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_37,
          _column_38,
          _column_39,
          _column_40,
          _column_41,
          _column_42,
          _column_43,
          _column_44,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get fechaInicio =>
      columnsByName['fecha_inicio']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fechaFin =>
      columnsByName['fecha_fin']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get activo =>
      columnsByName['activo']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>('id', aliasedName, false,
        hasAutoIncrement: true,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT');
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>('nombre', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>('fecha_inicio', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>('fecha_fin', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>('activo', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0 CHECK (activo IN (0, 1))',
        defaultValue: const i1.CustomExpression('0'));

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get semesterId =>
      columnsByName['semester_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get profesor =>
      columnsByName['profesor']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get colorIndex =>
      columnsByName['color_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get limiteFaltas =>
      columnsByName['limite_faltas']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get creditos =>
      columnsByName['creditos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fechaLimiteCancelacion =>
      columnsByName['fecha_limite_cancelacion']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get archivada =>
      columnsByName['archivada']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cancelada =>
      columnsByName['cancelada']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fechaCancelacion =>
      columnsByName['fecha_cancelacion']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>('semester_id', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL REFERENCES semesters(id)');
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>('profesor', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>('color_index', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>('limite_faltas', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 6',
        defaultValue: const i1.CustomExpression('6'));
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>('creditos', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>('fecha_limite_cancelacion', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>('archivada', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0 CHECK (archivada IN (0, 1))',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>('cancelada', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0 CHECK (cancelada IN (0, 1))',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>('fecha_cancelacion', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get poligonoJson =>
      columnsByName['poligono_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>('poligono_json', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get codigo =>
      columnsByName['codigo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get edificio =>
      columnsByName['edificio']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get piso =>
      columnsByName['piso']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get indicaciones =>
      columnsByName['indicaciones']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get lat =>
      columnsByName['lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lng =>
      columnsByName['lng']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get campusId =>
      columnsByName['campus_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>('codigo', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>('edificio', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>('piso', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>('indicaciones', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<double> _column_19(String aliasedName) =>
    i1.GeneratedColumn<double>('lat', aliasedName, true,
        type: i1.DriftSqlType.double, $customConstraints: 'NULL');
i1.GeneratedColumn<double> _column_20(String aliasedName) =>
    i1.GeneratedColumn<double>('lng', aliasedName, true,
        type: i1.DriftSqlType.double, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>('campus_id', aliasedName, true,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NULL REFERENCES campuses(id)');

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get subjectId =>
      columnsByName['subject_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get diaSemana =>
      columnsByName['dia_semana']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get horaInicio =>
      columnsByName['hora_inicio']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get horaFin =>
      columnsByName['hora_fin']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get roomId =>
      columnsByName['room_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fechaDesde =>
      columnsByName['fecha_desde']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fechaHasta =>
      columnsByName['fecha_hasta']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>('subject_id', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL REFERENCES subjects(id)');
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>('dia_semana', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>('hora_inicio', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>('hora_fin', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>('room_id', aliasedName, true,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NULL REFERENCES rooms(id)');
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>('fecha_desde', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>('fecha_hasta', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fecha =>
      columnsByName['fecha']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get estado =>
      columnsByName['estado']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get marcadaEn =>
      columnsByName['marcada_en']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>('session_id', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL REFERENCES class_sessions(id)');
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>('fecha', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>('estado', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>('marcada_en', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get subjectId =>
      columnsByName['subject_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get porcentaje =>
      columnsByName['porcentaje']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get nota =>
      columnsByName['nota']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get fecha =>
      columnsByName['fecha']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get orden =>
      columnsByName['orden']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<double> _column_33(String aliasedName) =>
    i1.GeneratedColumn<double>('porcentaje', aliasedName, false,
        type: i1.DriftSqlType.double, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<double> _column_34(String aliasedName) =>
    i1.GeneratedColumn<double>('nota', aliasedName, true,
        type: i1.DriftSqlType.double, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>('fecha', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>('orden', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0',
        defaultValue: const i1.CustomExpression('0'));

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get bufferMinutos =>
      columnsByName['buffer_minutos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get modoTransporte =>
      columnsByName['modo_transporte']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get direccionCasa =>
      columnsByName['direccion_casa']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get homeLat =>
      columnsByName['home_lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get homeLng =>
      columnsByName['home_lng']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get tema =>
      columnsByName['tema']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get limiteFaltasPorDefecto =>
      columnsByName['limite_faltas_por_defecto']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>('id', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 1',
        defaultValue: const i1.CustomExpression('1'));
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>('buffer_minutos', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 5',
        defaultValue: const i1.CustomExpression('5'));
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>('modo_transporte', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>('direccion_casa', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<double> _column_41(String aliasedName) =>
    i1.GeneratedColumn<double>('home_lat', aliasedName, true,
        type: i1.DriftSqlType.double, $customConstraints: 'NULL');
i1.GeneratedColumn<double> _column_42(String aliasedName) =>
    i1.GeneratedColumn<double>('home_lng', aliasedName, true,
        type: i1.DriftSqlType.double, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>('tema', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>('limite_faltas_por_defecto', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 6',
        defaultValue: const i1.CustomExpression('6'));

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    semesters,
    subjects,
    campuses,
    rooms,
    classSessions,
    sessionInstances,
    evaluations,
    tasks,
    userSettings,
  ];
  late final Shape0 semesters = Shape0(
      source: i0.VersionedTable(
        entityName: 'semesters',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 subjects = Shape1(
      source: i0.VersionedTable(
        entityName: 'subjects',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_5,
          _column_1,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 campuses = Shape2(
      source: i0.VersionedTable(
        entityName: 'campuses',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 rooms = Shape3(
      source: i0.VersionedTable(
        entityName: 'rooms',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 classSessions = Shape4(
      source: i0.VersionedTable(
        entityName: 'class_sessions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_22,
          _column_23,
          _column_24,
          _column_25,
          _column_26,
          _column_27,
          _column_28,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 sessionInstances = Shape5(
      source: i0.VersionedTable(
        entityName: 'session_instances',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(session_id, fecha)',
        ],
        columns: [
          _column_0,
          _column_29,
          _column_30,
          _column_31,
          _column_32,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 evaluations = Shape6(
      source: i0.VersionedTable(
        entityName: 'evaluations',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_22,
          _column_1,
          _column_33,
          _column_34,
          _column_35,
          _column_36,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 tasks = Shape8(
      source: i0.VersionedTable(
        entityName: 'tasks',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_22,
          _column_45,
          _column_35,
          _column_46,
          _column_47,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 userSettings = Shape9(
      source: i0.VersionedTable(
        entityName: 'user_settings',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_37,
          _column_38,
          _column_39,
          _column_40,
          _column_41,
          _column_42,
          _column_43,
          _column_44,
          _column_48,
          _column_49,
          _column_50,
          _column_51,
          _column_52,
          _column_53,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get subjectId =>
      columnsByName['subject_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get titulo =>
      columnsByName['titulo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get fecha =>
      columnsByName['fecha']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get hecha =>
      columnsByName['hecha']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get creadaEn =>
      columnsByName['creada_en']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>('titulo', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>('hecha', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0 CHECK (hecha IN (0, 1))',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_47(String aliasedName) => i1.GeneratedColumn<
        int>('creada_en', aliasedName, false,
    type: i1.DriftSqlType.int,
    $customConstraints:
        'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
    defaultValue: const i1.CustomExpression(
        'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)'));

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get bufferMinutos =>
      columnsByName['buffer_minutos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get modoTransporte =>
      columnsByName['modo_transporte']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get direccionCasa =>
      columnsByName['direccion_casa']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get homeLat =>
      columnsByName['home_lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get homeLng =>
      columnsByName['home_lng']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get tema =>
      columnsByName['tema']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get limiteFaltasPorDefecto =>
      columnsByName['limite_faltas_por_defecto']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get mascotaEsquina =>
      columnsByName['mascota_esquina']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get alarmaDespertar =>
      columnsByName['alarma_despertar']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get alarmaDespertarMin =>
      columnsByName['alarma_despertar_min']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get alarmaSalir =>
      columnsByName['alarma_salir']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get alarmaEvaluaciones =>
      columnsByName['alarma_evaluaciones']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get avisoEvaluacionMin =>
      columnsByName['aviso_evaluacion_min']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>('mascota_esquina', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints:
            'NOT NULL DEFAULT 1 CHECK (mascota_esquina IN (0, 1))',
        defaultValue: const i1.CustomExpression('1'));
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>('alarma_despertar', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints:
            'NOT NULL DEFAULT 1 CHECK (alarma_despertar IN (0, 1))',
        defaultValue: const i1.CustomExpression('1'));
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>('alarma_despertar_min', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 60',
        defaultValue: const i1.CustomExpression('60'));
i1.GeneratedColumn<int> _column_51(String aliasedName) =>
    i1.GeneratedColumn<int>('alarma_salir', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 1 CHECK (alarma_salir IN (0, 1))',
        defaultValue: const i1.CustomExpression('1'));
i1.GeneratedColumn<int> _column_52(String aliasedName) =>
    i1.GeneratedColumn<int>('alarma_evaluaciones', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints:
            'NOT NULL DEFAULT 1 CHECK (alarma_evaluaciones IN (0, 1))',
        defaultValue: const i1.CustomExpression('1'));
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>('aviso_evaluacion_min', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 1200',
        defaultValue: const i1.CustomExpression('1200'));

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    semesters,
    subjects,
    campuses,
    rooms,
    classSessions,
    sessionInstances,
    evaluations,
    tasks,
    userSettings,
  ];
  late final Shape0 semesters = Shape0(
      source: i0.VersionedTable(
        entityName: 'semesters',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 subjects = Shape1(
      source: i0.VersionedTable(
        entityName: 'subjects',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_5,
          _column_1,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 campuses = Shape2(
      source: i0.VersionedTable(
        entityName: 'campuses',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 rooms = Shape3(
      source: i0.VersionedTable(
        entityName: 'rooms',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 classSessions = Shape4(
      source: i0.VersionedTable(
        entityName: 'class_sessions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_22,
          _column_23,
          _column_24,
          _column_25,
          _column_26,
          _column_27,
          _column_28,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 sessionInstances = Shape5(
      source: i0.VersionedTable(
        entityName: 'session_instances',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(session_id, fecha)',
        ],
        columns: [
          _column_0,
          _column_29,
          _column_30,
          _column_31,
          _column_32,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 evaluations = Shape6(
      source: i0.VersionedTable(
        entityName: 'evaluations',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_22,
          _column_1,
          _column_33,
          _column_34,
          _column_35,
          _column_36,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 tasks = Shape8(
      source: i0.VersionedTable(
        entityName: 'tasks',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_22,
          _column_45,
          _column_35,
          _column_46,
          _column_47,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape10 userSettings = Shape10(
      source: i0.VersionedTable(
        entityName: 'user_settings',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_37,
          _column_38,
          _column_39,
          _column_54,
          _column_40,
          _column_41,
          _column_42,
          _column_43,
          _column_44,
          _column_48,
          _column_49,
          _column_50,
          _column_51,
          _column_52,
          _column_53,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get bufferMinutos =>
      columnsByName['buffer_minutos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get modoTransporte =>
      columnsByName['modo_transporte']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get trayectoMinutos =>
      columnsByName['trayecto_minutos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get direccionCasa =>
      columnsByName['direccion_casa']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get homeLat =>
      columnsByName['home_lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get homeLng =>
      columnsByName['home_lng']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get tema =>
      columnsByName['tema']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get limiteFaltasPorDefecto =>
      columnsByName['limite_faltas_por_defecto']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get mascotaEsquina =>
      columnsByName['mascota_esquina']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get alarmaDespertar =>
      columnsByName['alarma_despertar']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get alarmaDespertarMin =>
      columnsByName['alarma_despertar_min']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get alarmaSalir =>
      columnsByName['alarma_salir']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get alarmaEvaluaciones =>
      columnsByName['alarma_evaluaciones']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get avisoEvaluacionMin =>
      columnsByName['aviso_evaluacion_min']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>('trayecto_minutos', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    semesters,
    subjects,
    campuses,
    rooms,
    classSessions,
    sessionInstances,
    evaluations,
    tasks,
    userSettings,
  ];
  late final Shape0 semesters = Shape0(
      source: i0.VersionedTable(
        entityName: 'semesters',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 subjects = Shape1(
      source: i0.VersionedTable(
        entityName: 'subjects',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_5,
          _column_1,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 campuses = Shape2(
      source: i0.VersionedTable(
        entityName: 'campuses',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 rooms = Shape3(
      source: i0.VersionedTable(
        entityName: 'rooms',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 classSessions = Shape4(
      source: i0.VersionedTable(
        entityName: 'class_sessions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_22,
          _column_23,
          _column_24,
          _column_25,
          _column_26,
          _column_27,
          _column_28,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 sessionInstances = Shape5(
      source: i0.VersionedTable(
        entityName: 'session_instances',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(session_id, fecha)',
        ],
        columns: [
          _column_0,
          _column_29,
          _column_30,
          _column_31,
          _column_32,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 evaluations = Shape6(
      source: i0.VersionedTable(
        entityName: 'evaluations',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_22,
          _column_1,
          _column_33,
          _column_34,
          _column_35,
          _column_36,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 tasks = Shape8(
      source: i0.VersionedTable(
        entityName: 'tasks',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_22,
          _column_45,
          _column_35,
          _column_46,
          _column_47,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape11 userSettings = Shape11(
      source: i0.VersionedTable(
        entityName: 'user_settings',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_37,
          _column_38,
          _column_39,
          _column_54,
          _column_40,
          _column_55,
          _column_41,
          _column_42,
          _column_43,
          _column_44,
          _column_48,
          _column_49,
          _column_50,
          _column_51,
          _column_52,
          _column_53,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get bufferMinutos =>
      columnsByName['buffer_minutos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get modoTransporte =>
      columnsByName['modo_transporte']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get trayectoMinutos =>
      columnsByName['trayecto_minutos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get direccionCasa =>
      columnsByName['direccion_casa']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get detectarCasa =>
      columnsByName['detectar_casa']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get homeLat =>
      columnsByName['home_lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get homeLng =>
      columnsByName['home_lng']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get tema =>
      columnsByName['tema']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get limiteFaltasPorDefecto =>
      columnsByName['limite_faltas_por_defecto']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get mascotaEsquina =>
      columnsByName['mascota_esquina']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get alarmaDespertar =>
      columnsByName['alarma_despertar']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get alarmaDespertarMin =>
      columnsByName['alarma_despertar_min']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get alarmaSalir =>
      columnsByName['alarma_salir']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get alarmaEvaluaciones =>
      columnsByName['alarma_evaluaciones']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get avisoEvaluacionMin =>
      columnsByName['aviso_evaluacion_min']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_55(String aliasedName) =>
    i1.GeneratedColumn<int>('detectar_casa', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints:
            'NOT NULL DEFAULT 0 CHECK (detectar_casa IN (0, 1))',
        defaultValue: const i1.CustomExpression('0'));

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    semesters,
    subjects,
    campuses,
    rooms,
    classSessions,
    sessionInstances,
    evaluations,
    tasks,
    userSettings,
    trips,
  ];
  late final Shape0 semesters = Shape0(
      source: i0.VersionedTable(
        entityName: 'semesters',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 subjects = Shape1(
      source: i0.VersionedTable(
        entityName: 'subjects',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_5,
          _column_1,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 campuses = Shape2(
      source: i0.VersionedTable(
        entityName: 'campuses',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 rooms = Shape3(
      source: i0.VersionedTable(
        entityName: 'rooms',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 classSessions = Shape4(
      source: i0.VersionedTable(
        entityName: 'class_sessions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_22,
          _column_23,
          _column_24,
          _column_25,
          _column_26,
          _column_27,
          _column_28,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 sessionInstances = Shape5(
      source: i0.VersionedTable(
        entityName: 'session_instances',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(session_id, fecha)',
        ],
        columns: [
          _column_0,
          _column_29,
          _column_30,
          _column_31,
          _column_32,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 evaluations = Shape6(
      source: i0.VersionedTable(
        entityName: 'evaluations',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_22,
          _column_1,
          _column_33,
          _column_34,
          _column_35,
          _column_36,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 tasks = Shape8(
      source: i0.VersionedTable(
        entityName: 'tasks',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_22,
          _column_45,
          _column_35,
          _column_46,
          _column_47,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape12 userSettings = Shape12(
      source: i0.VersionedTable(
        entityName: 'user_settings',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_37,
          _column_38,
          _column_39,
          _column_54,
          _column_40,
          _column_56,
          _column_57,
          _column_58,
          _column_59,
          _column_60,
          _column_55,
          _column_41,
          _column_42,
          _column_43,
          _column_61,
          _column_62,
          _column_63,
          _column_44,
          _column_48,
          _column_49,
          _column_50,
          _column_51,
          _column_52,
          _column_53,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape13 trips = Shape13(
      source: i0.VersionedTable(
        entityName: 'trips',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_64,
          _column_65,
          _column_66,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get bufferMinutos =>
      columnsByName['buffer_minutos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get modoTransporte =>
      columnsByName['modo_transporte']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get trayectoMinutos =>
      columnsByName['trayecto_minutos']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get direccionCasa =>
      columnsByName['direccion_casa']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get aprenderTrayecto =>
      columnsByName['aprender_trayecto']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get rutaPieMin =>
      columnsByName['ruta_pie_min']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get rutaCarroMin =>
      columnsByName['ruta_carro_min']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get enCaminoDesde =>
      columnsByName['en_camino_desde']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get enCaminoModo =>
      columnsByName['en_camino_modo']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get detectarCasa =>
      columnsByName['detectar_casa']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get homeLat =>
      columnsByName['home_lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get homeLng =>
      columnsByName['home_lng']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get tema =>
      columnsByName['tema']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get temaPaleta =>
      columnsByName['tema_paleta']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get temaPapel =>
      columnsByName['tema_papel']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get temaAcento =>
      columnsByName['tema_acento']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get limiteFaltasPorDefecto =>
      columnsByName['limite_faltas_por_defecto']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get mascotaEsquina =>
      columnsByName['mascota_esquina']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get alarmaDespertar =>
      columnsByName['alarma_despertar']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get alarmaDespertarMin =>
      columnsByName['alarma_despertar_min']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get alarmaSalir =>
      columnsByName['alarma_salir']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get alarmaEvaluaciones =>
      columnsByName['alarma_evaluaciones']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get avisoEvaluacionMin =>
      columnsByName['aviso_evaluacion_min']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_56(String aliasedName) =>
    i1.GeneratedColumn<int>('aprender_trayecto', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints:
            'NOT NULL DEFAULT 1 CHECK (aprender_trayecto IN (0, 1))',
        defaultValue: const i1.CustomExpression('1'));
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>('ruta_pie_min', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>('ruta_carro_min', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_59(String aliasedName) =>
    i1.GeneratedColumn<int>('en_camino_desde', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>('en_camino_modo', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>('tema_paleta', aliasedName, false,
        type: i1.DriftSqlType.string,
        $customConstraints: 'NOT NULL DEFAULT \'papiro\'',
        defaultValue: const i1.CustomExpression('\'papiro\''));
i1.GeneratedColumn<int> _column_62(String aliasedName) =>
    i1.GeneratedColumn<int>('tema_papel', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_63(String aliasedName) =>
    i1.GeneratedColumn<int>('tema_acento', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get salida =>
      columnsByName['salida']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get llegada =>
      columnsByName['llegada']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get modo =>
      columnsByName['modo']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_64(String aliasedName) =>
    i1.GeneratedColumn<int>('salida', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_65(String aliasedName) =>
    i1.GeneratedColumn<int>('llegada', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_66(String aliasedName) =>
    i1.GeneratedColumn<int>('modo', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
}) =>
    i0.VersionedSchema.stepByStepHelper(
        step: migrationSteps(
      from1To2: from1To2,
      from2To3: from2To3,
      from3To4: from3To4,
      from4To5: from4To5,
      from5To6: from5To6,
    ));
